name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Runs go tests
        run: go test -cover

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: staticcheck
        run: go version

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      
      - name: gosec
        run: gosec ./...